repos:
  - repo: https://github.com/cpp-linter/cpp-linter-hooks
    rev: v0.6.1
    hooks:
      - id: clang-format
        args: [--style=Google]
  
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.6
    hooks:
      - id: ruff
        types_or: [ python, pyi ]
        args: [ --fix ]
      - id: ruff-format
        types_or: [ python, pyi ]